name: "TVHeadend"
guid: "3fd018e5-5e78-4e58-b280-a0c068febee0"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvheadend.png"
version: 11
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Manage TVHeadend from Jellyfin"
description: "Manage TVHeadend from Jellyfin"
category: "LiveTV"
artifacts:
  - "TVHeadEnd.dll"
changelog: |2-
  ### Bug Fixes ###
  - Fix DLNA streaming (#46) @jkellerer

  ### Code or Repo Maintenance ###
  - Use meta ci (#55) @crobibero

  ### CI & build changes ###
  - fix: meta ci workflows (#56) @h1dden-da3m0n
  - Use meta ci (#55) @crobibero
